version = 1
# subconverterå¤–éƒ¨é…ç½®ï¼ˆTerminalï¼‰
# å‚è€ƒï¼šhttps://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.toml
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# èŠ‚ç‚¹ç­›é€‰ï¼ˆåªå–å¸¸ç”¨åœ°åŒºï¼šé¦™æ¸¯ã€å°æ¹¾ã€æ–°åŠ å¡ã€æ—¥æœ¬ã€ç¾å›½ï¼‰
include_remarks = [
  "(é¦™æ¸¯|HK|((?i)Hong Kong)|ğŸ‡­ğŸ‡°|å°æ¹¾|TW|((?i)Taiwan)|ğŸ‡¹ğŸ‡¼|ç‹®åŸ|æ–°åŠ å¡|SG|((?i)Singapore)|ğŸ‡¸ğŸ‡¬|æ—¥æœ¬|JP|((?i)Japan)|ğŸ‡¯ğŸ‡µ|ç¾å›½|US|((?i)United States)|ğŸ‡ºğŸ‡²)"
]


# ä¸»ç­–ç•¥ç»„
[[custom_groups]]
name = "ğŸš€ ä»£ç†åŠ é€Ÿ"
type = "select"
rule = [
  "[]ğŸš© é¦™æ¸¯é€‰æ‹©",
  "[]ğŸŒ å°æ¹¾é€‰æ‹©",
  "[]ğŸ¦ ç‹®åŸé€‰æ‹©",
  "[]ğŸ‘º æ—¥æœ¬é€‰æ‹©",
  "[]ğŸ—½ ç¾å›½é€‰æ‹©",
  "[]DIRECT"
]

[[custom_groups]]
name = "ğŸ¤– äººå·¥æ™ºèƒ½"
type = "select"
rule = [
  "[]ğŸš© é¦™æ¸¯é€‰æ‹©",
  "[]ğŸŒ å°æ¹¾é€‰æ‹©",
  "[]ğŸ¦ ç‹®åŸé€‰æ‹©",
  "[]ğŸ‘º æ—¥æœ¬é€‰æ‹©",
  "[]ğŸ—½ ç¾å›½é€‰æ‹©",
  "[]DIRECT"
]

[[custom_groups]]
name = "ğŸ“º å›½å¤–åª’ä½“"
type = "select"
rule = [
  "[]ğŸš© é¦™æ¸¯é€‰æ‹©",
  "[]ğŸŒ å°æ¹¾é€‰æ‹©",
  "[]ğŸ¦ ç‹®åŸé€‰æ‹©",
  "[]ğŸ‘º æ—¥æœ¬é€‰æ‹©",
  "[]ğŸ—½ ç¾å›½é€‰æ‹©",
  "[]DIRECT"
]

[[custom_groups]]
name = "ğŸŒ å›½å†…ç«™ç‚¹"
type = "select"
rule = [ "[]DIRECT", "[]ğŸš€ ä»£ç†åŠ é€Ÿ" ]

[[custom_groups]]
name = "ğŸ¬ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = [ "[]ğŸš€ ä»£ç†åŠ é€Ÿ", "[]DIRECT" ]


# åœ°åŒºé€‰æ‹©ç­–ç•¥ç»„
[[custom_groups]]
name = "ğŸš© é¦™æ¸¯é€‰æ‹©"
type = "select"
rule = [ "[]âš¡ é¦™æ¸¯è‡ªåŠ¨", "(é¦™æ¸¯|HK|((?i)Hong Kong)|ğŸ‡­ğŸ‡°)" ]

[[custom_groups]]
name = "ğŸŒ å°æ¹¾é€‰æ‹©"
type = "select"
rule = [ "[]âš¡ å°æ¹¾è‡ªåŠ¨", "(å°æ¹¾|TW|((?i)Taiwan)|ğŸ‡¹ğŸ‡¼)" ]

[[custom_groups]]
name = "ğŸ¦ ç‹®åŸé€‰æ‹©"
type = "select"
rule = [ "[]âš¡ ç‹®åŸè‡ªåŠ¨", "(ç‹®åŸ|æ–°åŠ å¡|SG|((?i)Singapore)|ğŸ‡¸ğŸ‡¬)" ]

[[custom_groups]]
name = "ğŸ‘º æ—¥æœ¬é€‰æ‹©"
type = "select"
rule = [ "[]âš¡ æ—¥æœ¬è‡ªåŠ¨", "(æ—¥æœ¬|JP|((?i)Japan)|ğŸ‡¯ğŸ‡µ)" ]

[[custom_groups]]
name = "ğŸ—½ ç¾å›½é€‰æ‹©"
type = "select"
rule = [ "[]âš¡ ç¾å›½è‡ªåŠ¨", "(ç¾å›½|US|((?i)United States)|ğŸ‡ºğŸ‡²)" ]


# åœ°åŒºå»¶è¿Ÿè‡ªåŠ¨æµ‹è¯•ç­–ç•¥ç»„ï¼ˆæ¯9sæµ‹è¯•ä¸€æ¬¡ï¼Œå®¹å·®12msï¼‰
[[custom_groups]]
name = "âš¡ é¦™æ¸¯è‡ªåŠ¨"
type = "url-test"
rule = [ "(é¦™æ¸¯|HK|((?i)Hong Kong)|ğŸ‡­ğŸ‡°)" ]
url = "http://www.google.com/generate_204"
interval = 9
tolerance = 12

[[custom_groups]]
name = "âš¡ å°æ¹¾è‡ªåŠ¨"
type = "url-test"
rule = [ "(å°æ¹¾|TW|((?i)Taiwan)|ğŸ‡¹ğŸ‡¼)" ]
url = "http://www.google.com/generate_204"
interval = 9
tolerance = 12

[[custom_groups]]
name = "âš¡ ç‹®åŸè‡ªåŠ¨"
type = "url-test"
rule = [ "(ç‹®åŸ|æ–°åŠ å¡|SG|((?i)Singapore)|ğŸ‡¸ğŸ‡¬)" ]
url = "http://www.google.com/generate_204"
interval = 9
tolerance = 12

[[custom_groups]]
name = "âš¡ æ—¥æœ¬è‡ªåŠ¨"
type = "url-test"
rule = [ "(æ—¥æœ¬|JP|((?i)Japan)|ğŸ‡¯ğŸ‡µ)" ]
url = "http://www.google.com/generate_204"
interval = 9
tolerance = 12

[[custom_groups]]
name = "âš¡ ç¾å›½è‡ªåŠ¨"
type = "url-test"
rule = [ "(ç¾å›½|US|((?i)United States)|ğŸ‡ºğŸ‡²)" ]
url = "http://www.google.com/generate_204"
interval = 9
tolerance = 12


# è§„åˆ™é›†ï¼ˆæ›´æ–°é—´éš”ä¸º120ç§’ï¼‰
[[rulesets]]
group = "DIRECT"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/lan-domain.yaml"
interval = 120

[[rulesets]]
group = "ğŸ¤– äººå·¥æ™ºèƒ½"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/ai.yaml"
interval = 120

[[rulesets]]
group = "ğŸ“º å›½å¤–åª’ä½“"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/global-media-domain.yaml"
interval = 120

[[rulesets]]
group = "ğŸš€ ä»£ç†åŠ é€Ÿ"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/google-domain.yaml"
interval = 120

[[rulesets]]
group = "ğŸš€ ä»£ç†åŠ é€Ÿ"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/proxy-domain.yaml"
interval = 120

[[rulesets]]
group = "ğŸŒ å›½å†…ç«™ç‚¹"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/cn-domain.yaml"
interval = 120

[[rulesets]]
group = "DIRECT"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/lan-ip.yaml"
interval = 120

[[rulesets]]
group = "ğŸ“º å›½å¤–åª’ä½“"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/global-media-ip.yaml"
interval = 120

[[rulesets]]
group = "ğŸš€ ä»£ç†åŠ é€Ÿ"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/google-ip.yaml"
interval = 120

[[rulesets]]
group = "ğŸŒ å›½å†…ç«™ç‚¹"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ¬ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
